from __future__ import annotations

from pathlib import Path

from gui_contract_common import (
    base_single_species_fit_config,
    write_json_payload,
)

from odefit.api.backend import (
    fit_global_observables_from_config,
    parse_model_text,
)
from odefit.api.project_io import (
    attach_result_payload,
    create_project,
    save_project,
)
from odefit.api.serialization import backend_output_payload


def main() -> None:
    config = base_single_species_fit_config()

    model_text = Path(config["model"]).read_text()

    parsed_model = parse_model_text(
        model_text,
        name="single_step",
    )

    parsed_model_path = write_json_payload(
        parsed_model,
        "gui_contract_parsed_model.json",
    )

    output = fit_global_observables_from_config(config)

    payload = backend_output_payload(
        output,
        workflow="fit",
        max_rows=10,
    )

    fit_payload_path = write_json_payload(
        payload,
        "gui_contract_fit_payload.json",
    )

    project = create_project(
        name="GUI Contract Fit Example",
        description="Example GUI project containing config and fit payload.",
        workflow="fit",
        config=config,
        ui_state={
            "active_tab": "fit",
            "selected_time_column": "time",
            "selected_signal_columns": None,
        },
        notes=[
            "Generated by gui_contract_parse_fit_save.py",
        ],
        tags=[
            "gui-contract",
            "fit",
            "hsqc",
            "variable-projection",
        ],
    )

    attach_result_payload(
        project=project,
        result_payload=payload,
    )

    project_path = save_project(
        project=project,
        file_path="examples/backend_api/outputs/gui_contract_fit_project.modeler.json",
    )

    print(f"Wrote parsed model payload to: {parsed_model_path}")
    print(f"Wrote fit payload to: {fit_payload_path}")
    print(f"Wrote project file to: {project_path}")


if __name__ == "__main__":
    main()
